### ISSUE TITLE
Small clarification

### ISSUE THREAD

**Issue by dutta-alankar** [idefix-code/idefix#11]
I was trying to add `xdmf` io on `idefix` and for that reason, I was looking into the source code. I have a small confusion and I think @glesur or @neutrinoceros can help me with this. 
In `src/output/vtk.cpp`, I came across line 142:
```
nodestart[2-dir] = datain.gbeg[dir]-datain.nghost[dir];
```
I'm confused with the minus sign in here. Shouldn't `nghost` be added so that in the dump, the ghost cells are neglected?

**Comment by glesur** [comment]
`gbeg` is the global index of the first active cell of the current sudomain. Since we only save active cells in dump files, the global index in the dumpfile (`nodestart`) is the global index of the first cell (`gbeg`) minus the number of ghost cell at the beginning of the domain (`nghost`). The scheme provided in the [grid subsection](https://idefix.readthedocs.io/en/latest/programmingguide.html#grid) of the programming guide might be helpful.

**Comment by neutrinoceros** [comment]
>  Shouldn't nghost be added so that in the dump, the ghost cells are neglected?

ghost cells are by definition redundant and can be reconstructed at restart, which is why they are not included in dumps. Furthermore, we actively try to keep output files (dumps and vtks) agnostic with respect to the domain decomposition.

**Comment by dutta-alankar** [comment]
That was helpful. Also wanted to ask regarding xdmf io in `idefix`. I have made the basic framework for this ready. But needs a lot of testing right now. The data is almost identical to `PLUTO` dumps and use Parallel HDF5 io. Would you be interested in having this feature in `idefix`? Then I can open a PR soon. However, since I'm new to `C++` this is semi-baked and would need some time to mature fully.
