### ISSUE TITLE
BUG: non-reproductibility of spherical MHD runs with resistivity and axis BC on single GPU

### ISSUE THREAD

**Issue by jeankpf** [idefix-code/idefix#239]
### Describe the issue:

Hello,

I recently stumbled upon a bug of non-reproductibility in IDEFIX: when AXIS boundary conditions are activated together with magnetic resistivity (no matter the integration scheme) in spherical geometry MHD runs, the outputs (data.0001.vtk for example) provided by the code can differ when the same executable is run consecutively (while the initial state being the same, that is data.0000.vtk do not differ, but the following data.000*.vtk might). Actually, without looking at the vtk outputs, this behavior is already visible during the run: the divB values displayed in live can differ for consecutive runs at similar times.

Additionally, an intestering behavior of this bug goes as follows. When magnetic resistivity is deactivated (but the axis BC kept), the divB values between consecutive runs can differ from each other, but the vtk outputs do not. So my guess would be that the magnetic field might not be always correctly reconstructed at the pole ghost interfaces, which would impact the computation of the current J and div B, but in practice it would impact the vtk outputs only when J is used to evolve B (that is when the resistivity is activated for example, div B being never directly used to evolve any quantity in the code).

Many thanks for any inputs you might be able to provide, I attached to this bug report the setup.cpp, definitions.hpp and idefix.ini that I used to reproduce this bug the simplest way (they must be used with a reconstruction scheme that only needs 2 ghost cells).

[reproduced.zip](https://github.com/idefix-code/idefix/files/15095560/reproduced.zip)

### runtime information:

Idefix version 2.0.00-6f79142
Built against Kokkos 40100
Reproduced on a single GPU (both on Olympe/V100 and Adastra/MI250X), but not on a single CPU, so the matter looks like it is GPU related.

**Comment by glesur** [comment]
Hi @jeankpf, it seems that your initial conditions are different between each trial when running on a GPU. A way to see this is at the end of your initflow method, after `d.SyncToDevice()` dump the datablock to a file:
`data.DumpToFile("Init");`
This will create a file "Init.0.0.idfx" which is the binary image of the datablock in GPU memory. If you compare 2 such dumps (with diff), they differ. So the problem lies in your initial condition, apparently. I would start with this before invoking axis boundary issues.

**Comment by glesur** [comment]
Hi @jeankpf , unfortunately, this is the cost of doing GPU computing, and it's not a bug in Idefix. This comes from the fact that the axis boundary conditions need to do some average to regularise the pole. This is particularly true for the radial EMF and the radial current, both localised on cell edges, and in particular on the axis.

To make sure that each cell edge touching the axis share the same EMF (and current), Idefix uses an averaging procedure over all of these edges. The problem of this average is that one cannot predict in which order the GPU will perform the sum (the order of the operations in an idefix_for is never guaranteed) as we use atomic operations for this. As it so happens, depending on the GPU internal scheduler, some cells might be treated before others. Worse, the gpu can use the fmad operation, which fuses a multiply and an addition with additional precision, hence affecting the roundoff error.

This is what is happening in your case. The boundaries are totally reproducible if we comment out these averaging operations (ie calls to `Axis::SymmetrizeEx1Side` and `Axis::RegularizeCurrentSide`), but otherwise, some roundoff errors are to be expected every now and then.

The question is: is this a problem for your application?

**Comment by jeankpf** [comment]
Hello @glesur, and thank you very much for the explanation. Non-reproducibility is not so much of a problem for my current application, as long as it is under control and that we have a satisfying explanation as for why such a behaviour is observed. So no more problem here, you can close the issue as far as I am concerned. Thanks again!
